// 指令宏定义

#define         ECT_FRONT_MOVE                                1                  // 正向移动
#define         ECT_BACK_MOVE                                 2                  // 反向移动
#define         ECT_MOVETO                                    3                  // 移动到
#define         ECT_READ_FLASH                                4                  // 读取flash
#define         ECT_WRITE_FLASH                               5                  // 写入flash
#define         ECT_POWERON_RESET                             6                  // 上电复位
#define         ECT_GET_ABSOL_POS                             7                  // 获取绝对位置参数
#define         ECT_SET_IO_HEIGHT                             8                  // 设置IO高电平
#define         ECT_SET_IO_LOW                                9                  // 设置IO低电平
#define         ECT_GET_IO                                    10                 // 获取IO电平
#define         ECT_RUN                                       11                 // 启动
#define         ECT_STOP                                      12                 // 停止
#define         ECT_GET_RUN_STOP                              13                 // 获取启动/停止
#define         ECT_SET_PWM                                   14                 // 设置PWM参数
#define         ECT_GET_PWM                                   15                 // 获取PWM参数
#define         ECT_READ_CONFIG                               16                 // 读配置文件
#define         ECT_WRITE_CONFIG                              17                 // 写配置文件
#define         ECT_WASHSTA_RESET                             18                 // 清洗站复位
#define         ECT_WASHSTA_WASH                              19                 // 清洗站清洗
#define         ECT_R1_POWERON_RESET                          20                 // R1上电复位
#define         ECT_R2_POWERON_RESET                          21                 // R2上电复位
#define         ECT_LOAD_ARM_RESET                            22                 // 加样臂宏指令复位
#define         ECT_INCUBATOR_RESET                           23                 // 孵育盘复位
#define         ECT_REA_LOADER_RESET                          24                 // 试剂在线加载复位
#define         ECT_REA_LOADER_TRANS                          25                 // 试剂在线加载传输电机
#define         ECT_REA_CABIN_RESET                           26                 // 试剂仓复位宏指令
#define         ECT_REA_CABIN_RUN                             27                 // 试剂仓运动宏指令
#define         ECT_R1_MOVETO_GET_POS                         28                 // R1水平移动到取试剂位
#define         ECT_R1_MOVETO_ADD_POS                         29                 // R1水平运动到加试剂位
#define         ECT_R2_MOVETO_GET_POS                         30                 // R2水平移动到取试剂位
#define         ECT_R2_MOVETO_ADD_POS                         31                 // R2水平运动到加试剂位
#define         ECT_SAMPLE_INJECT_RESET                       32                 // 进样器复位宏指令
#define         ECT_LOAD_ARM_MOVETO_WASH                      33                 // 加样臂宏指令移动到洗针位5ul
#define         ECT_LOAD_ARM_MOVETO_ABSORB                    34                 // 加样臂宏指令移动到吸样位5ul
#define         ECT_LOAD_ARM_MOVETO_LET                       35                 // 加样臂宏指令移动到排样位5ul
#define         ECT_SAMPLE_ARM_MOVETO_ABSORB                  36                 // 样本臂稀释移动到吸稀释剂位5ul
#define         ECT_ISE_MOVETO_ABSORB                         37                 // ISE移动到吸样位
#define         ECT_ISE_MOVETO_ADD                            38                 // ISE移动到加样位
#define         ECT_CROSS_MACH_MOVETO_ABSORB                  39                 // 横向电机运动到取样位宏指令
#define         ECT_CROSS_MACH_MOVETO_TEST                    40                 // 横向电机移动到检测样本管类型位宏指令
#define         ECT_SAMPLE_RACK_MOVETO_SCAN                   41                 // 样本架移动到扫码位置
#define         ECT_CROSS_MACH_MOVETO_SCAN                    42                 // 横向电机移动到扫码位
#define         ECT_CROSS_MACH_MOVETO_OUT_RACK                43                 // 横向电机运输样本架到出架位置宏指令
#define         ECT_CROSS_MACH_MOVETO_CALI                    44                 // 横向电机移动到校准位置（宏指令）
#define         ECT_LOAD_ARM_CS_WASH                          45                 // 加样臂超声清洗
#define         ECT_SET_ELEC                                  46                 // 设置泵电压
#define         ECT_GET_ELEC                                  47                 // 获取泵电压
#define         ECT_REA_LOADER_OPEN_TRAK                      48                 // 试剂在线加载打开滑轨
#define         ECT_REA_LOADER_CLOSE_TRAK                     49                 // 试剂在线加载关闭滑轨
#define         ECT_BASET_PUSH_IN_RACK                        50                 // 提篮推手进架
#define         ECT_CACHE_SAMPLE_IN_RACK                      51                 // 缓存区样本架进架
#define         ECT_DISPATCH_SAM_NORMAL_IN_RACK               52                 // 调度接口样本架常规进架
#define         ECT_OUTRACK_MACH_TRANS_SAM_RACK_POS           53                 // 出架电机运输样本架到出架位（远距离）
#define         ECT_OUTRACK_MACH_RESET                        54                 // 出架电机复位
#define         ECT_R1_LEVEL_MOVETO_R2_REA_POS                55                 // R1水平移动到取R2试剂位
#define         ECT_ISE_LOAD_ARM_RESET                        56                 // ISE加样臂复位
#define         ECT_ISE_MOVETO_WASH                           57                 // ISE移动到洗针位
#define         ECT_ISE_MOVETO_LET                            58                 // ISE移动到排样位
#define         ECT_ELE_CALI                                  59                 // 电流标定
#define         ECT_TRACK_RESET                               60                 // 传输轨道复位
